general:
  python_version: "3.12"
  random_seed: 42

paths:
  raw_data: "src/data/raw"
  processed_data: "src/data/processed"
  features_dir: "src/features"
  model_dir: "src/models/saved"

training:
  model_type: "random_forest"
  random_forest:
    n_estimators: 200
    max_depth: 20
    n_jobs: -1

evaluation:
  threshold_soft: 0.80   # только лог
  threshold_hard: 0.95   # autoblock (пока не используется)

logging:
  level: "INFO"